project:
  type: website
  output-dir: docs
  
website:
  title: "Hannah's Way Cool Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/twitter_is_for_losers
      - icon: github
        href: https://github.com/hgossner/special-octo-broccoli
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Hannah Gossner"

format:
  html:
    theme: yeti
    toc: true

editor: source

